name: a

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  a:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: a
      run: swift build -v
    - name: Run tests
      run: swift test -v
