name: CD
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  deploy-Development:
    runs-on: macos-latest
    environment:
      name: Development
      url: 'www.google.com.br'
    needs: build
    steps:
    - name: Run a one-line script
      run: echo Deploy Development

  deploy-Homologate:
    runs-on: macos-latest
    environment:
      name: Homologate
      url: 'www.google.com.br'
    needs: deploy-Development
    steps:
    - name: Run a one-line script
      run: echo Deploy Homologate

  deploy-Production:
    runs-on: macos-latest
    environment:
      name: Homologate
      url: 'www.google.com.br'
    needs: deploy-Homologate
    steps:
    - name: Run a one-line script
      run: echo Deploy Production
