name: CD
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  Build-Project:
    name: Build in iPhone 8
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: xcodebuild 
          -project "TesteUnitario.xcodeproj" -scheme "TesteUnitario" -destination "platform=iOS Simulator,name=iPhone 8" -configuration Release build
          
  Test-Project:
    name: Unitary Test
    runs-on: macos-latest
    needs: Build-Project
    steps:
      - name: Test
        run: xcodebuild -scheme "TesteUnitario" -destination "platform=iOS Simulator,name=iPhone 8" test

  Deploy-Development:
    runs-on: macos-latest
    environment:
      name: Development
      url: 'www.google.com.br'
    needs: Test-Project
    steps:
    - name: Run a one-line script
      run: echo Deploy Development

  Deploy-Homologate:
    runs-on: macos-latest
    environment:
      name: Homologate
      url: 'www.google.com.br'
    needs: Deploy-Development
    steps:
    - name: Run a one-line script
      run: echo Deploy Homologate

  Deploy-Production:
    runs-on: macos-latest
    environment:
      name: Homologate
      url: 'www.google.com.br'
    needs: Deploy-Homologate
    steps:
    - name: Run a one-line script
      run: echo Deploy Production
