name: Continuous Integration

on: [push]
##  pull_request:
##    branches:
##      - main
##      - developer

jobs:
  iOS:
    name: Test iOS
    runs-on: macos-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build
        run: xcodebuild 
          -project "TesteUnitario.xcodeproj" 
          -scheme "TesteUnitario" 
          -destination "platform=iOS Simulator,name=iPhone 8"
          -configuration Release build
          
      - name: Test
        run: xcodebuild
          -scheme "TesteUnitario" 
          -destination "platform=iOS Simulator,name=iPhone 8"
          test
