name: Continuous Integration

on: [push]
##  pull_request:
##    branches:
##      - main
##      - developer

jobs:

  Build-Project:
    name: Build in iPhone 8
    runs-on: macos-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build
        run: xcodebuild -project "TesteUnitario.xcodeproj" -scheme "TesteUnitario" -destination "platform=iOS Simulator,name=iPhone 8" -configuration Release build
          
  Unitary-Test:
    name: Unitary Test in iPhone 8
    runs-on: macos-latest
    needs: Build-Project
    steps:
      - name: Unitary Test iPhone 8
        run: xcodebuild
          -scheme "TesteUnitario"
          -destination "platform=iOS Simulator,name=iPhone 8"
          test
