name: Continuous Integration

on: [push]
##  pull_request:
##    branches:
##      - main
##      - developer

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
     
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
     
    - name: Build and Test
      run: xcodebuild clean build test -project TesteUnitario/TesteUnitario.xcodeproj -scheme "TesteUnitario" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
