name: Continuous Integration

on: [push]
##  pull_request:
##    branches:
##      - main
##      - developer

jobs:
  iOS:
    name: Test iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: xcodebuild 
          -project "TesteUnitario.xcodeproj" 
          -scheme "TesteUnitario" 
          -destination "generic/platform=iOS"
          -configuration Release build CODE_SIGNING_ALLOWED=NO
      - name: Test
        run: xcodebuild
          -project "TesteUnitario.xcodeproj" 
          -scheme "TesteUnitario" 
          -destination "generic/platform=iOS"
          -configuration Release test CODE_SIGNING_ALLOWED=NO
